### ISSUE TITLE
demo应用打开白屏

### ISSUE THREAD

**Issue by weifengHuang** [ice-lab/react-materials#201]
效果：
![image](https://user-images.githubusercontent.com/25242467/149646012-7be891e9-2b22-4691-8579-f78adc89b236.png)

复现方式：
npm init ice icejs-electron --template @icedesign/scaffold-electron
cd icejs-electron/
tnpm start  

原因分析：
![image](https://user-images.githubusercontent.com/25242467/149645955-fb92cc35-8912-45ff-847f-edef155949a3.png)

process.env.__IS_SERVER__ 一直都是字符串的'false' ， 导致直接return

**Comment by luhc228** [comment]
关注这个 PR https://github.com/ice-lab/react-materials/pull/200，应该是这个问题引起的。

**Comment by imsobear** [comment]
新版脚手架已修复，已有项目可以参考上面的 PR 改一下。
