### ISSUE TITLE
init项目后，npm start报错

### ISSUE THREAD

**Issue by antstudio-git** [ice-lab/react-materials#203]
npm install 显示成功

npm start启动失败
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again

node 版本： v16.14.0

**Comment by imsobear** [comment]
重新装依赖。

**Comment by antstudio-git** [comment]
> 重新装依赖。

重新装过了，rm -rf node_modules以后装的，一样的错误

**Comment by imsobear** [comment]
用 cnpm 装试下，总之看起来这是依赖安装问题，跟框架没啥关系。
